<a href="https://colab.research.google.com/github/NgocAnhNguyen-0601/-Crypto-Currency-Bitcoin-Price-Prediction-/blob/main/crypto_currency_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
plt.style.use('fivethirtyeight')

In [2]:
end = datetime.now()
start = datetime(end.year-15, end.month, end.day)
stock = 'BTC-USD'
stock_data = yf.download(stock, start = start, end = end)

/tmp/ipykernel_805/1837361621.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stock_data = yf.download(stock, start = start, end = end)
[*********************100%***********************]  1 of 1 completed

In [3]:
stock_data.head()

Price            Close        High         Low        Open    Volume
Ticker         BTC-USD     BTC-USD     BTC-USD     BTC-USD   BTC-USD
Date
2014-09-17  457.334015  468.174011  452.421997  465.864014  21056800
2014-09-18  424.440002  456.859985  413.104004  456.859985  34483200
2014-09-19  394.795990  427.834991  384.532013  424.102997  37919700
2014-09-20  408.903992  423.295990  389.882996  394.673004  36863600
2014-09-21  398.821014  412.425995  393.181000  408.084991  26580100

In [4]:
 stock_data.tail()

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2026-05-25,77279.929688,77804.921875,76833.039062,76981.125000,19808387601
2026-05-26,75825.734375,77990.867188,75569.468750,77280.125000,35999475458
2026-05-27,74344.703125,76014.296875,74136.500000,75825.304688,33802172927
2026-05-28,73536.554688,74460.125000,72493.414062,74339.570312,40148145327
2026-05-30,73669.109375,73675.976562,73331.015625,73369.125000,33406971904

In [5]:
stock_data.describe().T

,,count,mean,std,min,25%,50%,75%,max
Price,Ticker,,,,,,,,
Close,BTC-USD,4273.0,2.857248e+04,3.242990e+04,1.781030e+02,3.448117e+03,1.151260e+04,4.630645e+04,1.247525e+05
High,BTC-USD,4273.0,2.912147e+04,3.297115e+04,2.117310e+02,3.495175e+03,1.180006e+04,4.731383e+04,1.261981e+05
Low,BTC-USD,4273.0,2.795642e+04,3.183972e+04,1.715100e+02,3.372120e+03,1.124829e+04,4.470555e+04,1.231960e+05
Open,BTC-USD,4273.0,2.855632e+04,3.242600e+04,1.768970e+02,3.421910e+03,1.150283e+04,4.628085e+04,1.247521e+05
Volume,BTC-USD,4273.0,2.226533e+10,2.293002e+10,5.914570e+06,1.663280e+09,1.800070e+10,3.439874e+10,3.509679e+11

In [6]:
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4273 entries, 2014-09-17 to 2026-05-30
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Close, BTC-USD)   4273 non-null   float64
 1   (High, BTC-USD)    4273 non-null   float64
 2   (Low, BTC-USD)     4273 non-null   float64
 3   (Open, BTC-USD)    4273 non-null   float64
 4   (Volume, BTC-USD)  4273 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 200.3 KB

In [7]:
# Close Data Price
stock_data.columns
stock_data[['Close']]

Price              Close
Ticker           BTC-USD
Date
2014-09-17    457.334015
2014-09-18    424.440002
2014-09-19    394.795990
2014-09-20    408.903992
2014-09-21    398.821014
...                  ...
2026-05-25  77279.929688
2026-05-26  75825.734375
2026-05-27  74344.703125
2026-05-28  73536.554688
2026-05-30  73669.109375

[4273 rows x 1 columns]